name: estore_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  google_nav_bar: 5.0.5
  line_icons: 2.0.1
  iconly: 1.0.1
  carousel_pro_nullsafety: 1.0.2
  flutter_svg: any
  carousel_slider: 4.0.0
  cached_network_image: 3.2.0
  flutter_html: 2.2.1
  cat_avatar_generator: 0.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/fonts/
    - assets/img/
    - assets/img/cate/
  fonts: 
    - family: GESS
      fonts: 
        - asset: assets/fonts/GESS.otf
  uses-material-design: true

